---
  - name: Install docker compose
    gather_facts: Yes
    hosts: webserver

    tasks:
      - name: Ensure docker-compose is installed and available
        get_url:
          url: https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
          dest: /usr/local/bin/docker-compose
          mode: 0775
        become: yes

      - name: Creates docker-compose yaml project directory
        file:
          path: /etc/docker-compose/wp
          state: directory
        become: yes

      - name: Copy docker-compose-wp.yml
        copy:
          src: /home/zhopa/github/devops/ansible/rer-aws/compose/docker-compose-wp.yml 
          dest: /etc/docker-compose/wp/docker-compose-wp.yml
          owner: ec2-user
          group: ec2-user
          mode: 0600
          backup: yes
        become: yes

      - name: Run docker-compose file and start the container(s)
        command: docker-compose -f docker-compose-wp.yml up -d
          args:
            chdir: /etc/docker-compose/wp
        register: myoutput
        become: yes

