- hosts: localhost
  
  vars:
    apache_group: 
      Debian: "root" 
      RedHat: "apache"
    apache_ctl: 
      Debian: "/usr/sbin/apache2ctl"
      RedHat: "/usr/sbin/apachectl"

  tasks:
    - yum: pkg=httpd state=present
      when: ansible_os_family == "RedHat"

    - apt: update_cache=yes name="apache2" state=present
      when: ansible_os_family == "Debian"

    - name: Make an apachectl symlink that is the same between distros
      file: 
         state: link 
         src: "{{apache_ctl[ansible_os_family]}}"
         dest: /usr/local/bin/apachectl

    - name:  Apply index.html from template
      template: 
         src: index.j2 
         dest: /var/www/html/index.html
         group: "{{ apache_group[ansible_os_family] }}"
         mode: "0644"

    - name: Check if Apache is running
      shell: ps aux | grep httpd | grep -v grep
      ignore_errors: yes
      changed_when: false
      register: service_apache_status

    - name: Start Apache if not running
      shell: /usr/sbin/apachectl -k start
      when: service_apache_status.rc != 0

#    - name: Report status of Apache
#      fail:
#        msg: |
#          Service apache2 is not running.
#          Return code from `grep`:
#          {{ service_apache_status.rc }}
#      when: service_apache_status.rc != 0
